.\" Manpage for tin.
.\" Contact mozdrent@gmail.com.in to correct errors or typos.
.TH man 8 "17 July 2021" "devduild_alpha_0.0.2" "tin man page"
.SH NAME
tin \- a small text editor.
.SH SYNOPSIS
tin [FILENAME/FILEPATH]
.SH DESCRIPTION
tin is a small text editor written in C. tin does not depend on any library (not even curses). It uses fairly standard VT100 (and similar terminals) escape sequences. The project is in alpha stage.

Supported languages are

  C
  C++
  Python
  Rust

.SH OPTIONS
vtext does not take any options.
.SH SEE ALSO
https://github.com/BeanGreen247/tin
.SH BUGS
Crashes while changing window size. Have to fix it.
.SH AUTHOR
Thomas Mozdren (mozdrent@gmail.com)
